### ISSUE TITLE
Dynamic Content in Snap Confirmations

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-skunkworks#254] opened 2022-02-23 18:09 UTC
Certain data in a confirmation window may have to be fetched from an API and would either delay the confirmation appearing or would require updating the window in a blocking way. It should be possible to create a confirmation window and then inject asynchronous results into that window without blocking the UI. This could be used for dynamic price information, gas estimation, etc.

**Comment by ritave** [comment] 2022-09-23 13:35
Duplicate of #611

**Closed by ritave** 2022-09-23 13:35 UTC
Labels: duplicate, enhancement
