### ISSUE TITLE
Flask data store corruption

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps-skunkworks#363] opened 2022-04-15 02:40 UTC
I think I have managed to create a snap that is somehow corrupting the internal state of the browser extension, first I managed to break Flask so it failed to load and would just show a white screen when opening the extension. Attached is a screen recording showing the issue.

https://user-images.githubusercontent.com/238069/163509148-5edda8e0-7462-4e71-9bac-77cde3adf1be.mov

I had to re-install Flask to get past this problem and then I tried the same steps in my snap to see if I could reproduce the problem, this time I was presented with this error when I tried to connect:

```
inpage.js:1 MetaMask - RPC Error: Cannot read properties of undefined (reading 'mnemonic') 
{code: -32603, message: "Cannot read properties of undefined (reading 'mnemonic')", data: {…}}
code: -32603
data: {originalError: {…}}
message: "Cannot read properties of undefined (reading 'mnemonic')"
[[Prototype]]: Object
```

I am likely doing something wrong in the snap to cause this problem but want to report it here and keep track of my findings.

**Comment by FrederikBolding** [comment] 2022-04-18 08:27
Hey @tmpfs - Thanks for reporting! The first problem sounds bad, do you have a reliable way to reproduce that? The second problem is something we are aware of and fixing with #355.

**Comment by tmpfs** [comment] 2022-04-19 02:20
Sadly @FrederikBolding I don't have a way to reproduce it, I was trying to reproduce it when I hit the second error and haven't been able to make it happen again.

Just before it happened I executed some code that called `snap_manageState` with the `update` command so I suspect there may be a race condition writing that file which could cause it to get corrupted which in turn would prevent the browser extension from starting correctly. This is only a hunch and I haven't read the code so unfortunately no more insights at this stage. If I reproduce it again I will try to get some more diagnostic information for us.

**Comment by bowensanders** [comment] 2022-09-15 16:52
I have also been unable to produce this.

**Comment by ritave** [comment] 2022-09-15 16:57
I'm closing this issue due to lack of reproducibility and no repeat occurrences. Please open a new issue if this happens again.

**Closed by ritave** 2022-09-15 16:57 UTC
Labels: bug, needs more information
